package com.ecommerce;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

//Generated by Spring
//@SpringBootApplication annotation is equivalent to using 
//@Configuration, @EnableAutoConfiguration, and @ComponentScan with their default attributes
@SpringBootApplication
public class EcommerceApplication {
	// main() method uses Spring Boot’s SpringApplication.run() method to launch an
	// application
	public static void main(String[] args) {
		SpringApplication.run(EcommerceApplication.class, args);
	}

}
